language: elixir
elixir:
  - 1.5.2
  - 1.6.0
otp_release:
  - 20.2
sudo: false
services:
  - postgresql
env:
  - MIX_ENV=test
cache:
  directories:
    - .dialyzer
before_script:
  - export PLT_FILENAME=elixir-${TRAVIS_ELIXIR_VERSION}_${TRAVIS_OTP_RELEASE}.plt
  - export PLT_LOCATION=/home/travis/$PLT_FILENAME
  - wget -O $PLT_LOCATION https://raw.github.com/danielberkompas/travis_elixir_plts/master/$PLT_FILENAME
script:
  - mix deps.get
  - mix compile
  - mix ecto.setup
  - mix dialyzer --no_check_plt --plt $PLT_LOCATION --no_native _build/test/lib/filterable/ebin
  - mix format --check-formatted --dry-ru
  - mix credo
  - mix coveralls.travis
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
