language: elixir
elixir:
  - 1.5.0
  - 1.6.0
otp_release:
  - 20.0
sudo: false
services:
  - postgresql
env:
  - MIX_ENV=test
cache:
  directories:
    - .dialyzer
script:
  - mix deps.get
  - mix compile
  - mix ecto.setup
  - mix dialyzer
  - mix format --check-formatted --dry-ru
  - mix credo
  - mix coveralls.travis
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
