language: elixir
elixir:
  - 1.4.0
  - 1.3.4
otp_release:
  - 19.2
  - 18.3
sudo: false
services:
  - postgresql
env:
  - MIX_ENV=test
script:
  - mix deps.get
  - mix compile
  - mix ecto.setup
  - mix coveralls.travis
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
