language: elixir
elixir:
  - 1.4.0
  - 1.3.4
otp_release:
  - 19.2
  - 18.3
sudo: false
services:
  - postgresql
env:
  - MIX_ENV=test
script:
  - "mix do deps.get, compile, ecto.setup, coveralls.travis"
