language: elixir
elixir:
  - 1.7.3
otp_release:
  - 20.2
sudo: false
services:
  - postgresql
env:
  - MIX_ENV=test
script:
  - mix deps.get
  - mix compile
  - mix ecto.setup
  - mix format --check-formatted --dry-run
  - mix credo
  - mix coveralls.travis
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
